# Generated by Django 4.2.7 on 2024-01-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
